### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials to leverage/use services and information that are exclusively available to registered users.

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#1]
Acceptance Criteria
- [x] Upon successful user registration, the dashboard is shown, and the user is automatically logged in.
- [x] Upon failure, an error is displayed, and the user is redirected (back) to the register
- [x] The username has to be unique
- [x] Logged-in users can log out and log back into their registered profile.

Developement Tasks:
Client:
- [x] sopra-fs22-group-24/client#2
- [x] sopra-fs22-group-24/client#24
- [x] sopra-fs22-group-24/client#3
- [x] sopra-fs22-group-24/client#4

Server:
- [x] #36
- [x] #37

**Comment by maurohirt** [comment]
Client:
- [ ] Make Registration and Overview Page
- [ ] Authenticated Users can Acess/ get redirected to the overview page
- [ ] Unauthenticated Users get redirected to Login/registration Page
Server
- [ ]
