### ISSUE TITLE
As a player, I want to see, which players turn it is, who loses and who wins.

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#11]
Acceptance Criteria:

- [x] The user, whose turn it is, is pointed out by the game.
- [x] The game also shows which users lose and which user wins.

Development Tasks: 

- [x] sopra-fs22-group-24/client#15
- [x] sopra-fs22-group-24/server#56
- [x] sopra-fs22-group-24/server#57
