### ISSUE TITLE
As a logged-in user, I want to have an overview over the different game-lobbies that are open in order to select a game of my choosing

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#2]
Acceptance Criteria

- [x] A logged in user can go to the game overview page where the currently active games are shown
- [x] If no game is currently running, it is suggested to start a new game
- [x] A user can choose which button to press in order to navigate to the screen he wants to go to (users overview, plays overview, play rules).

Developement Tasks:

Client:
- [x] sopra-fs22-group-24/client#5

Server:
- [x] sopra-fs22-group-24/server#39
- [x] sopra-fs22-group-24/server#40
