### ISSUE TITLE
As a user I want the option to edit my profile in order to change my credentials

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#4]
Acceptance Criteria

- [x] After a user is logged in, they have access to their profile page
- [x] The username can not be changed after the registration

Developement Taks:

- [x] sopra-fs22-group-24/client#6
- [x] sopra-fs22-group-24/client#7
- [x] sopra-fs22-group-24/server#43
- [x] sopra-fs22-group-24/server#44
- [x] sopra-fs22-group-24/client#28
