### ISSUE TITLE
As a logged in user, I want to create a new game that other logged in users can join.

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#9]
Acceptance Criteria:

- [x] A logged in User can click a button, labeled “New Game”, to create a new Game. The user will be transferred to a lobby.
- [x] Other Users can see all open games on the main page.
- [x] If a User clicks on an open game they are transferred to the Lobby
- [x] The Creator can click a “start” button in the Lobby to finally start the game

Development Tasks:

- [x] sopra-fs22-group-24/client#10
- [x] sopra-fs22-group-24/client#11
- [x] sopra-fs22-group-24/client#12
- [x] sopra-fs22-group-24/server#50
- [x] sopra-fs22-group-24/server#51
- [x] sopra-fs22-group-24/server#52
